name: Setup unit test
description: Download Maven caches needed for unit tests

inputs:
  distribution:
    description: Java distribution.
    required: false
    default: temurin
  java-version:
    description: The Java version that is going to be set up.
    required: false
    default: "21"

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: ./.github/actions/java-setup
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - id: maven-cache
      name: Maven cache
      uses: ./.github/actions/maven-cache

    - id: download-keycloak
      name: Download Keycloak Maven artifacts
      uses: actions/download-artifact@v4
      with:
        name: m2-keycloak-client.tzts

    - id: extract-maven-artifacts
      name: Extract Keycloak Maven artifacts
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          choco install zstandard
        fi
        tar -C ~/ --use-compress-program="zstd -d" -xf m2-keycloak-client.tzts
