<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="{project_name} admin client"
priority=500
summary="Using the {project_name} admin client to access the {project_name} Admin REST API">

The {project_name} admin client is a Java library that facilitates the access and usage of the {project_name} Admin REST API.
The library requires Java 11 or higher at runtime (RESTEasy dependency enforces this requirement).
To use it from your application add a dependency on the `keycloak-admin-client` library.
For example using Maven:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-admin-client</artifactId>
    <version>${client_version}</version>
</dependency>
----

The following example shows how to use the Java client library to get the details of the master realm:

[source,java,subs="attributes+"]
----

import org.keycloak.admin.client.Keycloak;
import org.keycloak.representations.idm.RealmRepresentation;
...

Keycloak keycloak = Keycloak.getInstance(
    "http://localhost:8080",
    "master",
    "admin",
    "password",
    "admin-cli");
RealmRepresentation realm = keycloak.realm("master").toRepresentation();
----

Complete Javadoc for the admin client is available at {apidocs_link}[{apidocs_name}].

[[_admin_client_compatibility]]
== Compatibility with {project_name} server

{project_name} admin client aims to work with multiple versions of {project_name} server. Admin client may be supported with the newer versions of {project_name} server
released later than the client itself as well as with the older versions of the {project_name} server, which were released earlier.
This means that the Java fields of the underlying "representation" classes, which are representing JSON properties of the request/response body (like for example `RealmRepresentation` class
shown in the previous section) might not be exactly same for the client and the server.

To avoid compatibility issues, it is important that the class `com.fasterxml.jackson.databind.ObjectMapper`, which is used by the admin client under the covers, is initialized with these two properties:

```
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

If you are using the basic ways of admin client creation as described above, then these properties are added by default as admin client uses by default class `org.keycloak.admin.client.JacksonProvider` for creating `ObjectMapper`,
which adds these properties automatically. However if you are injecting your own `customJacksonProvider` when creating `Keycloak` object, then please make sure that object mapper is initialized with
the properties above if you want to avoid compatibility issues.

For example, let's assume that the admin client is instantiated in a way as described below with your own `MyCustomJacksonProvider` class:

[source,java,subs="attributes+"]
----
Keycloak.getInstance(
                "http://localhost:8080",
                "master",
                "admin",
                "admin",
                "admin-cli",
                null,
                null,
                new MyCustomJacksonProvider()
        );
----

In this case, please make sure that your class `MyCustomJacksonProvider` extends from the class `org.keycloak.admin.client.JacksonProvider` or make sure to configure the `ObjectMapper` manually in a way described above.
The similar care should be taken when using `KeycloakBuilder` to create the admin client and the RestEasy client is manually injected and created.

</@tmpl.guide>
