name: Keycloak client sync nightly

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout keycloak main
        uses: actions/checkout@v7
        with:
          repository: keycloak/keycloak

      - name: Setup Java
        id: setup-java
        uses: ./.github/actions/java-setup

      - name: Build Keycloak Locally
        run: |
          # just a simple build with sources
          ./mvnw -ntp install  -V -e -DskipTests -DskipExamples -Pjboss-release

      - name: Checkout keycloak-client repository
        uses: actions/checkout@v7

      - id: build-keycloak-client
        name: Build Keycloak Client libraries
        shell: bash
        run: mvn -B clean install dependency:resolve -Pnightly -DskipTests=true

      - name: Execute sync
        run: ./.github/scripts/sync-keycloak-sources.sh

      - name: Build Keycloak Client Libs again
        uses: ./.github/actions/build-keycloak-client

  client-tests:
    name: Client tests
    needs: build
    uses: ./.github/workflows/run-tests.yml

