name: X Environment setup

on:
  workflow_call:
    outputs:
      mvn-releases-url:
        description: "Maven Releases URL"
        value: ${{ jobs.env.outputs.mvn-releases-url }}
      mvn-snapshots-url:
        description: "Maven Snapshots URL"
        value: ${{ jobs.env.outputs.mvn-snapshots-url }}
      deploy-skip:
        value: ${{ jobs.env.outputs.depoly-skip }}

defaults:
  run:
    shell: bash

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      mvn-releases-url: ${{ env.mvn-releases-url }}
      mvn-snapshots-url: ${{ env.mvn-snapshots-url }}
      deploy-skip: ${{ env.deploy-skip }}
    steps:
      - id: load-env
        run: |
          cat .github/env/release-env | sed -r '/^\s*$/d' >> $GITHUB_ENV