name: X Keycloak Client

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      mvn-url:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
      deploy-skip:
        required: false
        type: string
        default: false
    secrets:
      GH_TOKEN:
        required: true
      MVN_USERNAME:
        required: true
      MVN_TOKEN:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          server-id: kc-rel-repository
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-client'
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}

      - name: Deploy to Maven
        env:
          MAVEN_ID: kc-rel-repository
          MAVEN_URL: ${{ inputs.mvn-url }}
          MAVEN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          MVN_HTTP_CONFIG="-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"
          mvn -s ./.github/mvn-rel-settings.xml -nsu -B -Pgpg,jboss-release,all -Djboss.releases.repo.id=$MAVEN_ID -Dmaven.deploy.skip=${{ inputs.deploy-skip }} -Djboss.releases.repo.url=${{ inputs.mvn-url }} -Djboss.snapshots.repo.id=$MAVEN_ID -Djboss.snapshots.repo.url=${{ inputs.mvn-url }} -DskipTests -DskipTestsuite -DretryFailedDeploymentCount=10 -DautoReleaseAfterClose=true $MVN_HTTP_CONFIG clean deploy | tee deploy.log

      - name: Show Maven artifacts
        run: |
          cat deploy.log | grep "Uploaded to" | grep -o "https://[^ ]*" | grep -v '.xml$' | grep -v '.asc$' | grep -v '.pom$' | grep -v 'javadoc.jar$' | grep -v 'sources.jar$' | xargs -I {} echo "{}  " >> $GITHUB_STEP_SUMMARY
